### ISSUE TITLE
Bad player names can cause it to crash

### ISSUE THREAD

**Issue by Synkstar** [startersclan/docker-hlstatsxce-daemon#20]
```daemon_1  | DBD::mysql::st execute failed: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb3_general_ci,COERCIBLE) for operation '=' at .//HLstats.plib line 185.
daemon_1  | Unable to execute query:
daemon_1  |
daemon_1  |                     SELECT
daemon_1  |                             playerId
daemon_1  |                     FROM
daemon_1  |                             hlstats_PlayerNames
daemon_1  |                     WHERE
daemon_1  |                             playerId = 45
daemon_1  |                             AND name ='ゴMr.B🖤ゴ
daemon_1  |
daemon_1  | Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb3_general_ci,COERCIBLE) for operation '='

**Comment by leojonathanoh** [comment]
It does. There are several bugs in the perl code, that need manual remedy. I needed to do quite a bit of fixing in my personal fork that is very messy. Hope you know perl enough to do some fixes :)

As for the error above, I believe you need to change the convert all collations in the DB tables to `utf8mb4_unicode_ci`.

**Comment by leojonathanoh** [comment]
Specifically, in [`install.sql`](https://github.com/startersclan/hlstatsx-community-edition/blob/master/sql/install.sql), you need to replace all instances of `DEFAULT CHARSET=utf8` with `DEFAULT CHARSET=utf8mb4` and `DEFAULT COLLATE=utf8` with `DEFAULT COLLATE=utf8mb4_unicode_ci`. This allow supporting special characters / emoji in player names all other text columns of DB tables. See https://stackoverflow.com/a/50264108 for more information. Hope it helps!

**Comment by leojonathanoh** [comment]
I really wish I could support the community with some of my personal modifications, but it really takes up a bit of time to clean up my code. In the meantime, there are some forks which might have fixed minor issues e.g. https://github.com/NomisCZ/hlstatsx-community-edition. :P

**Comment by leojonathanoh** [comment]
Hey @Synkstar, i've added fixes from my personal fork that fixed this error for me in the past, see the [readme](https://github.com/startersclan/docker-hlstatsxce-daemon/blob/d76381920d8719aecfaed79ac0217de6adc40443/README.md#q-error-unable-to-execute-query-illegal-mix-of-collations-or-similar) again. Hope it works for you!
